# Generated by Django 3.0.3 on 2020-02-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(max_length=250)),
                ('contact_phone', models.IntegerField(max_length=11)),
                ('contact_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
