# Generated by Django 3.0.3 on 2020-02-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.IntegerField(),
        ),
    ]
